name: Documentation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz
          python -m pip install --upgrade pip

      - name: Generate Doxygen HTML output
        working-directory: doxygen
        #run: doxygen Doxyfile
        run: python doxygen-build.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: doxygen/html
          allow_empty_commit: true
          full_commit_message: ${{ github.event.head_commit.message }}
